// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace BDScoreSystem.Data.Models;

public partial class BDScoreDbContext : DbContext
{
    public BDScoreDbContext()
    {
    }

    public BDScoreDbContext(DbContextOptions<BDScoreDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<DressageResult> DressageResults { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=DJFSOFTWARE\\SQLEXPRESS;Initial Catalog=Sandpit;Integrated Security=True;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<DressageResult>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Dressage__3214EC079C5C8329");

            entity.Property(e => e.Date).HasColumnType("datetime");
            entity.Property(e => e.Result).HasColumnType("decimal(18, 0)");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}