// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BDScoreSystem.Data.Models;

public partial class DressageResult
{
    public int Id { get; set; }

    public DateTime? Date { get; set; }

    public string Venue { get; set; }

    public string Judge { get; set; }

    public decimal? Result { get; set; }

    public int? Placing { get; set; }
}